# -*- coding: utf-8 -*-
"""GEN AI DOWNLOAD MODEL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z_X4bUOpXbHqAWs1ywQfk4yeyk9DuN2T
"""


from langchain_huggingface import ChatHuggingFace,HuggingFacePipeline
llm =HuggingFacePipeline.from_model_id(
    model_id="TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    task="text-generation",
    pipeline_kwargs=dict(
        max_new_tokens=512,
        do_sample=True,
        repetition_penalty=1.03
    )
)

chat_model=ChatHuggingFace(llm=llm)
result=chat_model.invoke("Write a poem",temperature=0.9)
print(result.content)



